# _config.yml
title: "AI"
baseurl: "/AIML"  # Very important! Must match your repository name
url: "https://malikattiq11.github.io"  # Your GitHub Pages URL

# Build settings
theme: minima
plugins:
  - jekyll-feed
  

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  


